"""Post-session BRD generation (STORY-008).

The LLM writes only the narrative sections (context, stakeholders, process
prose, NFRs, assumptions). The document skeleton, the functional-requirements
table with [mm:ss] evidence, decisions, and open items are assembled
deterministically from SessionState + the utterance log — so every requirement
is guaranteed to appear with evidence timestamps that exist in the session
(TS-008-01/02), regardless of LLM compliance.
"""
from __future__ import annotations

from typing import Any

from src.intelligence import prompts
from src.intelligence.providers import LlmProvider, ProviderError
from src.intelligence.state import Utterance, mmss
from src.sessions.store import SessionStore


def generate_brd(session_id: str, store: SessionStore, provider: LlmProvider) -> str:
    session = store.load_session(session_id)
    state: dict[str, Any] = session["state"]
    utterances: list[Utterance] = session["utterances"]
    times = {u.id: u.t0 for u in utterances}

    system, user = prompts.build_brd_prompt(state, utterances)
    try:
        narrative = provider.complete_json(system, user, prompts.BRD_SCHEMA_HINT,
                                           max_tokens=8192)
    except ProviderError:
        narrative = {}  # degrade to a state-only BRD rather than failing

    title = (narrative.get("title") or state.get("title")
             or "Business Requirements Document")
    duration = max((u.t1 for u in utterances), default=0.0)

    lines: list[str] = [
        f"# {title}",
        "",
        f"> Session `{session_id}` — started {session['meta'].get('started', 'n/a')}, "
        f"duration {mmss(duration)}, {len(utterances)} utterances. "
        "Generated by ReqPilot; evidence references are [mm:ss] transcript timestamps.",
        "",
    ]

    lines += _narrative_section("1. Context & Background", narrative.get("context"),
                                fallback="\n".join(f"- {b}" for b in state.get("summary", []))
                                or "_Not captured._")
    lines += _stakeholders_section(narrative.get("stakeholders"))
    lines += _narrative_section("3. Current Process", narrative.get("current_process"))
    lines += _narrative_section("4. Future Process", narrative.get("future_process"))
    lines += _diagrams_block(state.get("diagrams", []))
    lines += _requirements_section(state.get("requirements", []), times)
    lines += _nfr_section(narrative.get("non_functional"), state.get("gaps", []))
    lines += _decisions_section(state.get("decisions", []), times)
    lines += _list_section("7. Assumptions", narrative.get("assumptions"))
    lines += _open_items_section(state.get("open_questions", []), state.get("gaps", []))

    return "\n".join(lines).rstrip() + "\n"


def _evidence_refs(item: dict[str, Any], times: dict[int, float]) -> str:
    """[mm:ss] refs for the item's evidence utterances that exist in the log."""
    refs = [f"[{mmss(times[uid])}]" for uid in item.get("evidence_utterances", [])
            if uid in times]
    return " ".join(refs) if refs else "—"


def _narrative_section(heading: str, body: Any, fallback: str = "_Not captured._") -> list[str]:
    text = body.strip() if isinstance(body, str) and body.strip() else fallback
    return [f"## {heading}", "", text, ""]


def _stakeholders_section(stakeholders: Any) -> list[str]:
    lines = ["## 2. Stakeholders", ""]
    if isinstance(stakeholders, list) and stakeholders:
        for s in stakeholders:
            if isinstance(s, dict):
                name = s.get("name", "Unknown")
                interest = s.get("interest", "")
                lines.append(f"- **{name}** — {interest}" if interest else f"- **{name}**")
            elif isinstance(s, str):
                lines.append(f"- {s}")
    else:
        lines.append("_Not captured._")
    lines.append("")
    return lines


def _diagrams_block(diagrams: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for d in diagrams:
        lines += [f"### Process diagram: {d.get('title', d.get('id', ''))}", "",
                  "```mermaid", d.get("mermaid", "").rstrip(), "```", ""]
    return lines


def _requirements_section(requirements: list[dict[str, Any]],
                          times: dict[int, float]) -> list[str]:
    lines = ["## 5. Functional Requirements", ""]
    if not requirements:
        lines += ["_No requirements captured._", ""]
        return lines
    lines += ["| ID | Requirement | Status | Evidence |",
              "|----|-------------|--------|----------|"]
    for r in requirements:
        text = str(r.get("text", "")).replace("|", "\\|")
        lines.append(f"| {r.get('id', '')} | {text} | {r.get('status', '')} "
                     f"| {_evidence_refs(r, times)} |")
    lines.append("")
    return lines


def _nfr_section(non_functional: Any, gaps: list[dict[str, Any]]) -> list[str]:
    lines = ["## 6. Non-Functional Requirements", ""]
    stated = [s for s in (non_functional or []) if isinstance(s, str) and s.strip()]
    nfr_gaps = [g for g in gaps if g.get("category") == "nfr"]
    for s in stated:
        lines.append(f"- {s}")
    for g in nfr_gaps:
        lines.append(f"- _Gap {g.get('id', '')}:_ {g.get('text', '')}")
    if not stated and not nfr_gaps:
        lines.append("_None stated in the session._")
    lines.append("")
    return lines


def _decisions_section(decisions: list[dict[str, Any]],
                       times: dict[int, float]) -> list[str]:
    if not decisions:
        return []
    lines = ["### Decisions Made", ""]
    for d in decisions:
        lines.append(f"- **{d.get('id', '')}**: {d.get('text', '')} "
                     f"{_evidence_refs(d, times)}")
    lines.append("")
    return lines


def _list_section(heading: str, items: Any) -> list[str]:
    lines = [f"## {heading}", ""]
    entries = [s for s in (items or []) if isinstance(s, str) and s.strip()]
    if entries:
        lines += [f"- {s}" for s in entries]
    else:
        lines.append("_None recorded._")
    lines.append("")
    return lines


def _open_items_section(questions: list[dict[str, Any]],
                        gaps: list[dict[str, Any]]) -> list[str]:
    lines = ["## 8. Open Items", ""]
    open_questions = [q for q in questions if q.get("status") != "answered"]
    other_gaps = [g for g in gaps if g.get("category") != "nfr"]
    for q in open_questions:
        req = f" (re {q['requirement_id']})" if q.get("requirement_id") else ""
        lines.append(f"- [{q.get('status', 'suggested')}] {q.get('text', '')}{req}")
    for g in other_gaps:
        lines.append(f"- [gap/{g.get('category', '')}] {g.get('text', '')}")
    if not open_questions and not other_gaps:
        lines.append("_None — all questions answered and no gaps outstanding._")
    lines.append("")
    return lines
